added necessary compiler flag
Because -Werror is added, building this fails with
   ramap.c:704:7: error: ‘ras’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
I have added -Wno-error=maybe-uninitialized to circumvent this.